<?php

function dragoon_forms_block_info(){
	$block_forms = array();
	/*$forms['dragoon_problem'] = array(
		'title' => t('Start Problem'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array('dragoon_forms_problem_form'),
		'access callback' => TRUE,
		'file' => 'dragoon_forms_problem_open.inc',
	);*/

	$block_forms['dragoon_problem'] = array(
		'info' => 'For activity and mode selection opens a form for the user'
	);
    $block_forms['create_nonClass_folder'] = array(
        'info' => 'Creates a non class folder'
    );
    $block_forms['delete_nonClass_folder'] = array(
        'info' => 'Deletes a non class folder'
    );
    $block_forms['create_nonClass_model'] = array(
        'info' => 'Creates a Model in user folders'
    );
    $block_forms['manage_sharing'] = array(
        'info' => 'Enables sharing non class folders to the system users'
    );

	return $block_forms;
}

function dragoon_forms_block_view($delta = ''){
	$block_form = array();
    switch($delta){
		case "dragoon_problem":
			module_load_include('inc', 'dragoon_forms', 'dragoon_forms_problem_open');
			drupal_add_js(drupal_get_path('module', 'dragoon_forms').'/static/form_modal.js');
			//drupal_add_css(drupal_get_path('module', 'dragoon_forms').'/static/modal.css');
			$block_form['title'] = t("Start Problem");
			$block_form['content'] = drupal_get_form('dragoon_forms_problem_form');
            break;
        case "create_nonClass_folder":
            module_load_include('inc', 'dragoon_forms', 'dragoon_forms_nc_createFolder');
            drupal_add_js(drupal_get_path('module', 'dragoon_forms').'/static/nc_createFolder.js');
            $block_form['title'] = t("Create Folder");
            $block_form['content'] = drupal_get_form('dragoon_forms_ncCFolder_form');
            break;
        case "delete_nonClass_folder":
            module_load_include('inc', 'dragoon_forms', 'dragoon_forms_nc_deleteFolder');
            drupal_add_js(drupal_get_path('module', 'dragoon_forms').'/static/nc_deleteFolder.js');
            $block_form['title'] = t("Delete Folders/Models");
            $block_form['content'] = drupal_get_form('dragoon_forms_ncDelFolder_form');
            break;
        case "create_nonClass_model":
            module_load_include('inc','dragoon_forms', 'dragoon_forms_nc_createModel');
            drupal_add_js(drupal_get_path('module', 'dragoon_forms').'/static/nc_createModel.js');
            $block_form['title'] = t('Create Model');
            $block_form['content'] = drupal_get_form('dragoon_forms_ncCModel_form');
            break;
        case "manage_sharing":
            module_load_include('inc','dragoon_forms', 'dragoon_forms_nc_manageSharing');
            drupal_add_js(drupal_get_path('module', 'dragoon_forms').'/static/nc_manageSharing.js');
            drupal_add_js(drupal_get_path('module', 'NC_models').'/static/autoComplete.js');
            $block_form['title'] = t('Share Folders');
            $block_form['content'] = drupal_get_form('dragoon_forms_nc_sharing');
            break;
    }

	return $block_form;
}

function dragoon_forms_form_alter(&$form, $form_state, $form_id){
	switch($form_id){
		case "dragoon_forms_problem_form":
			$form['#action'] = '#';
			$form['#prefix'] = "<div id = 'dragoon_problem_wrapper' class = 'modal fade' role= 'dialog'><div class='modal-dialog'><div class='modal-content'><div class = 'modal-body'><span class = 'close' data-dismiss = 'modal'>x</span>";
			$form['#suffix'] = "</div></div></div></div>";
			$form['#attributes'] = array(
				//'onsubmit' => 'return false;',
				'id' => 'dragoon_problem_form'
			);
			$form['submit_button']['#attributes'] = array(
				'data-dismiss' => 'modal'
			);
			break;

        case "dragoon_forms_ncCFolder_form":
            $form['#action'] = '#';
            $form['#prefix'] = "<div id='createFolderModal' class='modal fade' role='dialog'><div class='modal-dialog'><div class='modal-content'><div class = 'modal-body'><span class = 'close' data-dismiss = 'modal'>x</span>";
            $form['#suffix'] = "</div></div></div></div>";
            $form['#attributes'] = array(
                //'onsubmit' => 'return false;',
                'id' => 'dragoon_ncCFolder_form'
            );
            $form['cancel_button']['#attributes'] = array(
                'data-dismiss' => 'modal',
            );
            break;
        case "dragoon_forms_ncDelFolder_form":
            $form['#action'] = '#';
            $form['#prefix'] = "<div id='deleteFolderModal' class='modal fade' role='dialog'><div class='modal-dialog'><div class='modal-content'><div class = 'modal-body'><span class = 'close' data-dismiss = 'modal'>x</span>";
            $form['#suffix'] = "</div></div></div></div>";
            $form['#attributes'] = array(
                //'onsubmit' => 'return false;',
                'id' => 'dragoon_ncDelFolder_form'
            );
            $form['submit_button']['#attributes'] = array(
                'data-dismiss' => 'modal',
                'data-toggle'=>"modal",
                'href'=> '#confirmDeleteModal',
            );
            $form['cancel_button']['#attributes'] = array(
                'data-dismiss' => 'modal',
            );
            break;
        case "dragoon_forms_ncCModel_form":
            $form['#prefix'] = "<div id='createModelModal' class='modal fade' role='dialog'><div class='modal-dialog'><div class='modal-content'><div class = 'modal-body'><span class = 'close' data-dismiss = 'modal'>x</span>";
            $form['#suffix'] = "</div></div></div></div>";
            $form['#attributes'] = array(
                'id' => 'dragoon_ncCModel_form',
            );
            $form['cancel_button']['#attributes'] = array(
                'data-dismiss' => 'modal',
            );

            break;
        case "dragoon_forms_nc_sharing":
            $form['#action'] = '#';
            $form['#prefix'] = "<div id='shareFolderModal' class='modal fade' role='dialog'><div class='modal-dialog'><div class='modal-content'><div class = 'modal-body'><span class = 'close' data-dismiss = 'modal'>x</span>";
            $form['#suffix'] = "</div></div></div></div>";
            $form['#attributes'] = array(
                //'onsubmit' => 'return false;',
                'id' => 'dragoon_nc_manageSharing'
            );
            //$form['#validate'] = array('dragoon_forms_sharing_validate');
            break;
    }
}
