<?php

function dragoon_forms_block_info(){
	$block_forms = array();
	/*$forms['dragoon_problem'] = array(
		'title' => t('Start Problem'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array('dragoon_forms_problem_form'),
		'access callback' => TRUE,
		'file' => 'dragoon_forms_problem_open.inc',
	);*/

	$block_forms['dragoon_problem'] = array(
		'info' => 'For activity and mode selection opens a form for the user'
	);

	return $block_forms;
}

function dragoon_forms_block_view($delta = ''){
	$block_form = array();
	switch($delta){
		case "dragoon_problem":
			module_load_include('inc', 'dragoon_forms', 'dragoon_forms_problem_open');
			drupal_add_js(drupal_get_path('module', 'dragoon_forms').'/static/form_modal.js');
			drupal_add_css(drupal_get_path('module', 'dragoon_forms').'/static/modal.css');
			$block_form['title'] = t("Start Problem");
			$block_form['content'] = drupal_get_form('dragoon_forms_problem_form');
	}

	return $block_form;
}

function dragoon_forms_form_alter(&$form, $form_state, $form_id){
	switch($form_id){
		case "dragoon_forms_problem_form":
			$form['#action'] = 'models';
			$form['#prefix'] = "<div id = 'dragoon_problem_wrapper' class = 'modal_wrapper' style ='display:none;'><span id = 'close_button' class = 'close'>x</span>";
			$form['#suffix'] = "</div></div>";
			break;
	}
}