<?php

function model_library_block_info(){
	$blocks = array();
	$blocks['published_problems'] = array(
		'info' => 'Block for published problems'
	);
    $blocks['non_class_models'] = array(
      'info' => 'Block lists non class models'
    );
    return $blocks;
}

function model_library_block_view($delta = ""){
	$block = array();
	switch ($delta){

		case "published_problems":
            $block['subject'] = t('Model Library');
			$parameters = array(
				'id' => 'problem',
				'href' => '#',
				'appendHref' => false,
				'addKey' => 'key',
				'addValue'=> 'value',
//				'otherHref' => ' #drag-main-sec',
				'otherTags' => 'class = "dragoon_problem" data-toggle = "modal" data-target = "#dragoon_problem_wrapper"',
			);
			$json = file_get_contents((array_key_exists('HTTPS', $_SERVER) && $_SERVER['HTTPS'] == 'on'?"https":"http")."://".$_SERVER['SERVER_NAME'].'/LaitsV3/www/public_problem_index.json');
            //$json = file_get_contents((array_key_exists('HTTPS', $_SERVER) && $_SERVER['HTTPS'] == 'on'?"https":"http")."://".$_SERVER['SERVER_NAME'].'/code/public_problem_index.json');
            $block['content'] = getHTMLStructure($json, $parameters);
			break;
        case "non_class_models":
            global $user;
            $block['subject'] = t('Custom Models');
            $parameters = array(
                'id' => 'nc_problem',
                'href' => '#',
                'appendHref' => false,
                'addKey' => 'key',
                'addValue'=> 'value',
//				'otherHref' => ' #drag-main-sec',
                'otherTags' => 'class = "dragoon_nc_problem" data-toggle = "modal" data-target = "#dragoon_problem_wrapper"',
            );
            if(user_is_logged_in()) {
                $json = loadNCModels($user->name,0);
                $block['content'] = getHTMLStructure($json, $parameters);
				if(arg(0) != "class"){
                	$additional = createAdditionalBlocks($block['content']);
                	$block['content'] = $block['content'].$additional;
				}
            }
            else
                $block['content'] = "Please Login to check your non class models";
            break;
    }

	return $block;
}
