<?php

function create_table_html($titles, $data){
	drupal_add_css(drupal_get_path('module', 'table').'/static/table.css');
	$count = count($titles);
	$width = 100/$count;
	$str = '<table class = "formatted_table"><tr>';
	foreach($titles as $title){
		$str .= '<th>'.$title.'</th>';
	}
	$str .= '</tr>';

	foreach($data as $row){
		$str .= '<tr>';
		foreach($row as $d){
			$str .= '<td>'.$d.'</td>';
		}
		$str .= '</tr>';
	}
	$str .= '</table>';

	return $str;
}
