<?php
	function getHTMLStructure(/* object */ $json, /* array */ $parameters){
		$GLOBALS['counter'] = 1;
		$data = json_decode($json, true);
		drupal_add_js(drupal_get_path('module', 'nested_accordion').'/static/accordion.js');
		drupal_add_css(drupal_get_path('module', 'nested_accordion').'/static/accordion.css');
		return substr(getString($data, '', $parameters), 0 , -13);
	}

	function getString(/* array */ $data, /* string */ $str = '', $parameters){
		foreach($data as $key=>$value){
            if(is_array($value)){
                $str .= "<div class = 'accordion'>\n";
                $str .= "<h2>".$key."</h2>\n";
                $str .= "<div class = 'pane'>\n";
                $str = getString($value, $str, $parameters);
            } else {
            	if(!array_key_exists('appendHref', $parameters) || $parameters['appendHref']){
	                $str .= '<p><a id = "'.$parameters['id'].$GLOBALS['counter']++.'" 
	                	href = "'.$parameters['href'].
						(array_key_exists('addKey', $parameters) ? ('&'.$parameters['addKey'].'='.$key) : '').
						(array_key_exists('addValue', $parameters) ? ('&'.$parameters['addValue'].'='.$value) : '').
						(array_key_exists('otherHref', $parameters) ? ($parameters['otherHref']) : '').'"'.
						(array_key_exists('otherTags', $parameters) ? (' '.$parameters['otherTags']): "").
						">".$key."</a></p>\n";
				} else {
					$str .= '<p><a id = "'.$parameters['id'].$GLOBALS['counter']++.'"
						href = '.$parameters['href'].' '.
						(array_key_exists('addKey', $parameters) ? ($parameters['addKey'].'= "'.$key.'" ') : '').
						(array_key_exists('addValue', $parameters) ? ($parameters['addValue'].'="'.$value.'"') : '').
						(array_key_exists('otherTags', $parameters) ? (' '.$parameters['otherTags']): "").
						">".$key."</a></p>\n";
				}
            }
        }

        $str .= "</div></div>\n";
        return $str;
	}

